//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UILanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UILanguage.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification results backup file not found.
        /// </summary>
        public static string CanNotFindCheckedResult {
            get {
                return ResourceManager.GetString("CanNotFindCheckedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file not found.
        /// </summary>
        public static string CanNotFindDatabase {
            get {
                return ResourceManager.GetString("CanNotFindDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed response backup file not found.
        /// </summary>
        public static string CanNotFindPrintedResponse {
            get {
                return ResourceManager.GetString("CanNotFindPrintedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification results.
        /// </summary>
        public static string CheckedResult {
            get {
                return ResourceManager.GetString("CheckedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the barcode verification process.
        /// </summary>
        public static string CompleteTheBarcodeVerificationProcess {
            get {
                return ResourceManager.GetString("CompleteTheBarcodeVerificationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database does not exist.
        /// </summary>
        public static string DatabaseDoesNotExist {
            get {
                return ResourceManager.GetString("DatabaseDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error from NN file.
        /// </summary>
        public static string DetectError {
            get {
                return ResourceManager.GetString("DetectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the camera connection.
        /// </summary>
        public static string PleaseCheckTheCameraConnection {
            get {
                return ResourceManager.GetString("PleaseCheckTheCameraConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the database connection !.
        /// </summary>
        public static string PleaseCheckTheDatabaseConnection {
            get {
                return ResourceManager.GetString("PleaseCheckTheDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the printer connection !.
        /// </summary>
        public static string PleaseCheckThePrinterConnection {
            get {
                return ResourceManager.GetString("PleaseCheckThePrinterConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the template !.
        /// </summary>
        public static string PleaseCheckTheTemplate {
            get {
                return ResourceManager.GetString("PleaseCheckTheTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select job for the system.
        /// </summary>
        public static string PleaseSeletedJobForTheSystem {
            get {
                return ResourceManager.GetString("PleaseSeletedJobForTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed response.
        /// </summary>
        public static string PrintedResponse {
            get {
                return ResourceManager.GetString("PrintedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some activation params are missing ! Please check again !.
        /// </summary>
        public static string SomeActivationParametersAreMissing {
            get {
                return ResourceManager.GetString("SomeActivationParametersAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some parameters are missing! Please check again !.
        /// </summary>
        public static string SomeParametersAreMissing {
            get {
                return ResourceManager.GetString("SomeParametersAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some print parameter are missing! please check again !.
        /// </summary>
        public static string SomePrintParametersAreMissing {
            get {
                return ResourceManager.GetString("SomePrintParametersAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one action selected !.
        /// </summary>
        public static string ThereMustBeAtLeastOneActionSelected {
            get {
                return ResourceManager.GetString("ThereMustBeAtLeastOneActionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access NN file.
        /// </summary>
        public static string UnableToAccess {
            get {
                return ResourceManager.GetString("UnableToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
